/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kai2nenobu' at '16/12/14 10:55' with Gradle 3.2.1
 *
 * @author kai2nenobu, @date 16/12/14 10:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
