/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kai2nenobu' at '16/12/14 12:11' with Gradle 2.14.1
 *
 * @author kai2nenobu, @date 16/12/14 12:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
